export type Asset = {
  id: string;
  slug: string;
  category: string;
  categoryColor: string;
  title: string;
  description: string;
  longDescription: string;
  includes: string[];
  format: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  sectors: string[];
  bestseller: boolean;
  pages?: number;
  lastUpdated: string;
  previewItems: string[];
};

export const assets: Asset[] = [
  {
    id: "1",
    slug: "msme-growth-strategy-playbook",
    category: "Strategy",
    categoryColor: "bg-eccellere-gold/20 text-eccellere-gold",
    title: "MSME Growth Strategy Playbook",
    description:
      "Complete playbook for market entry, competitive analysis, and growth planning tailored to Indian MSMEs.",
    longDescription:
      "The MSME Growth Strategy Playbook is the definitive guide for Indian small and mid-size businesses ready to scale. Built from 30+ real engagements, this 90-page playbook walks you through every stage of strategic planning — from diagnosing your competitive position to building a 12-month execution roadmap. Every framework is India-contextualised with sector-specific examples.",
    includes: [
      "90-page PDF playbook",
      "Competitive landscape mapping template",
      "Market sizing calculator (Excel)",
      "12-month execution roadmap template",
      "Growth metric tracker dashboard",
      "5 case studies from Indian MSMEs",
    ],
    format: "PDF",
    price: 2499,
    originalPrice: 3499,
    rating: 4.8,
    reviews: 124,
    sectors: ["Manufacturing", "Retail"],
    bestseller: true,
    pages: 90,
    lastUpdated: "Mar 2026",
    previewItems: [
      "Chapter 1: Diagnosing your current strategic position",
      "Chapter 2: Market sizing for Indian sectors",
      "Chapter 3: Competitive advantage frameworks",
      "Chapter 4: Growth vectors and prioritisation",
      "Chapter 5: 12-month execution planning",
    ],
  },
  {
    id: "2",
    slug: "ai-readiness-assessment-toolkit",
    category: "Agentic AI",
    categoryColor: "bg-eccellere-purple/20 text-eccellere-purple",
    title: "AI Readiness Assessment Toolkit",
    description:
      "Self-assessment tool with scoring framework, sector benchmarks, and personalised recommendations.",
    longDescription:
      "The AI Readiness Assessment Toolkit gives you a structured methodology to evaluate your organisation's readiness for AI adoption — before you invest a single rupee in technology. Used by 89 businesses across Manufacturing, Retail, and Logistics, this toolkit helps you identify gaps, benchmark against your sector, and build a prioritised AI roadmap.",
    includes: [
      "60-question self-assessment Excel workbook",
      "Auto-scoring dashboard with radar chart",
      "Sector benchmarks (Manufacturing, Retail, Logistics, Consumer Products)",
      "Gap analysis template",
      "AI use case prioritisation matrix",
      "90-day quick-start roadmap template",
    ],
    format: "Excel",
    price: 1999,
    rating: 4.9,
    reviews: 89,
    sectors: ["Manufacturing", "Retail", "Logistics"],
    bestseller: true,
    lastUpdated: "Feb 2026",
    previewItems: [
      "Module 1: AI Strategy & Leadership Readiness",
      "Module 2: Data Infrastructure Assessment",
      "Module 3: Process & Workflow Evaluation",
      "Module 4: People & Skills Gap Analysis",
      "Module 5: Technology & Integration Readiness",
    ],
  },
  {
    id: "3",
    slug: "lean-manufacturing-implementation-guide",
    category: "Process Transformation",
    categoryColor: "bg-eccellere-teal/20 text-eccellere-teal",
    title: "Lean Manufacturing Implementation Guide",
    description:
      "Step-by-step lean transformation for Indian factories, including 5S, Kaizen, and value stream mapping.",
    longDescription:
      "Transform your factory floor with this battle-tested lean implementation guide built specifically for Indian manufacturing SMEs. Unlike Western lean frameworks that assume large assembly lines, this guide adapts 5S, Kaizen, Kanban, and value stream mapping for the realities of Indian factories — seasonal workforce, mixed product lines, and constrained capital.",
    includes: [
      "120-page implementation guide (PDF)",
      "Value Stream Mapping templates (Visio + PDF)",
      "5S audit checklist and scoring sheet",
      "Kaizen event facilitation kit",
      "Kanban board setup guide",
      "OEE calculator (Excel)",
      "30-60-90 day implementation roadmap",
    ],
    format: "PDF + Template",
    price: 3499,
    rating: 4.7,
    reviews: 67,
    sectors: ["Manufacturing"],
    bestseller: false,
    pages: 120,
    lastUpdated: "Jan 2026",
    previewItems: [
      "Part 1: Lean principles for Indian factories",
      "Part 2: Value stream mapping in practice",
      "Part 3: 5S implementation step-by-step",
      "Part 4: Kaizen event planning and execution",
      "Part 5: Sustaining lean — culture and metrics",
    ],
  },
  {
    id: "4",
    slug: "ecommerce-launch-checklist",
    category: "Digital",
    categoryColor: "bg-eccellere-info/20 text-eccellere-info",
    title: "E‑Commerce Launch Checklist",
    description:
      "Everything you need to launch a D2C or marketplace presence — from platform choice to first 100 orders.",
    longDescription:
      "Stop paying agencies ₹5–10 lakh to set up what you can do yourself with the right guidance. This comprehensive checklist covers every decision point in your e-commerce launch — from choosing between Shopify, WooCommerce, and Meesho to setting up your first ad campaign and fulfiling your first 100 orders.",
    includes: [
      "200-point launch checklist (Excel)",
      "Platform comparison matrix",
      "Tech stack decision framework",
      "First 30 days launch calendar",
      "Category page copywriting guide",
      "Return policy template (India-compliant)",
    ],
    format: "Template",
    price: 999,
    rating: 4.6,
    reviews: 203,
    sectors: ["Retail", "Consumer Products"],
    bestseller: false,
    lastUpdated: "Feb 2026",
    previewItems: [
      "Phase 1: Platform selection and setup",
      "Phase 2: Product catalogue and content",
      "Phase 3: Payment, shipping, and returns",
      "Phase 4: Marketing and acquisition",
      "Phase 5: First orders and fulfilment",
    ],
  },
  {
    id: "5",
    slug: "ai-use-case-prioritisation-matrix",
    category: "Agentic AI",
    categoryColor: "bg-eccellere-purple/20 text-eccellere-purple",
    title: "AI Use Case Prioritisation Matrix",
    description:
      "Framework to identify, score, and prioritise AI use cases by ROI, feasibility, and strategic impact.",
    longDescription:
      "Most AI projects fail because businesses pick the wrong use cases first. This prioritisation matrix helps you identify 20–30 potential AI use cases in your business, score them across ROI potential, implementation feasibility, data readiness, and strategic alignment — and build a sequenced roadmap that delivers quick wins first.",
    includes: [
      "AI use case identification workbook (Excel)",
      "Scoring matrix with weighted criteria",
      "ROI estimation model",
      "60-point use case library by sector",
      "Implementation sequencing framework",
      "Presentation template for board/management",
    ],
    format: "Excel",
    price: 1499,
    rating: 4.5,
    reviews: 56,
    sectors: ["Manufacturing", "Logistics"],
    bestseller: false,
    lastUpdated: "Mar 2026",
    previewItems: [
      "Step 1: Use case discovery workshop template",
      "Step 2: Scoring criteria and weighting",
      "Step 3: Feasibility and data readiness check",
      "Step 4: ROI modelling and business case",
      "Step 5: Roadmap sequencing",
    ],
  },
  {
    id: "6",
    slug: "competitive-landscape-analyzer",
    category: "Strategy",
    categoryColor: "bg-eccellere-gold/20 text-eccellere-gold",
    title: "Competitive Landscape Analyzer",
    description:
      "Porter's Five Forces, SWOT, and PESTLE analysis templates pre-configured for Indian market context.",
    longDescription:
      "Understand your competitive position in depth with this analyst-grade toolkit. Pre-configured with Indian market data sources and sector-specific prompts, the Competitive Landscape Analyzer takes you from blank page to a comprehensive competitive assessment in under a week — without hiring a consultant.",
    includes: [
      "Porter's Five Forces template (customised for India)",
      "SWOT analysis workbook",
      "PESTLE framework with India-specific prompts",
      "Competitor profiling template (×10 competitors)",
      "Strategic group mapping worksheet",
      "Competitive positioning statement builder",
    ],
    format: "Toolkit",
    price: 2999,
    originalPrice: 4500,
    rating: 4.8,
    reviews: 91,
    sectors: ["All Sectors"],
    bestseller: true,
    lastUpdated: "Jan 2026",
    previewItems: [
      "Module 1: Porter's Five Forces analysis",
      "Module 2: SWOT with evidence-based scoring",
      "Module 3: PESTLE for India market context",
      "Module 4: Competitor profiling",
      "Module 5: Strategic positioning",
    ],
  },
  {
    id: "7",
    slug: "employee-capability-building-roadmap",
    category: "Organisation",
    categoryColor: "bg-amber-100 text-amber-700",
    title: "Employee Capability Building Roadmap",
    description:
      "Competency mapping, training needs analysis, and L&D strategy template for scaling teams.",
    longDescription:
      "As Indian MSMEs scale, the people strategy often lags behind business growth. This roadmap toolkit helps HR leaders and founders design a structured capability building programme — from competency mapping to L&D calendar — that actually improves business performance.",
    includes: [
      "Competency framework template (role-based)",
      "Training needs analysis (TNA) workbook",
      "L&D calendar planner",
      "Learning KPI tracker",
      "Budget planning template",
      "Facilitation guide for team managers",
    ],
    format: "Playbook",
    price: 1999,
    rating: 4.4,
    reviews: 43,
    sectors: ["Manufacturing", "Retail"],
    bestseller: false,
    lastUpdated: "Dec 2025",
    previewItems: [
      "Module 1: Competency framework design",
      "Module 2: Skills gap assessment",
      "Module 3: Training prioritisation",
      "Module 4: Delivery and facilitation",
      "Module 5: Measuring learning impact",
    ],
  },
  {
    id: "8",
    slug: "supply-chain-optimisation-toolkit",
    category: "Process Transformation",
    categoryColor: "bg-eccellere-teal/20 text-eccellere-teal",
    title: "Supply Chain Optimisation Toolkit",
    description:
      "End-to-end supply chain diagnostic, KPI dashboards, and improvement roadmap for mid-size businesses.",
    longDescription:
      "India's supply chain complexity is unique — seasonal demand swings, fragmented suppliers, unreliable logistics partners. This toolkit gives operations leaders a structured methodology to diagnose inefficiencies, benchmark against best-in-class, and build a prioritised improvement roadmap.",
    includes: [
      "Supply chain diagnostic questionnaire",
      "End-to-end process mapping templates",
      "50+ supply chain KPI dashboard (Excel)",
      "Supplier scoring and evaluation matrix",
      "Inventory optimisation calculator",
      "12-week improvement programme outline",
    ],
    format: "Toolkit",
    price: 4499,
    originalPrice: 6000,
    rating: 4.9,
    reviews: 78,
    sectors: ["Manufacturing", "Logistics", "Consumer Products"],
    bestseller: true,
    lastUpdated: "Mar 2026",
    previewItems: [
      "Phase 1: Supply chain diagnostic",
      "Phase 2: Demand and inventory analysis",
      "Phase 3: Supplier network evaluation",
      "Phase 4: Logistics and distribution review",
      "Phase 5: Improvement roadmap",
    ],
  },
  {
    id: "9",
    slug: "data-analytics-starter-kit",
    category: "Digital",
    categoryColor: "bg-eccellere-info/20 text-eccellere-info",
    title: "Data Analytics Starter Kit for MSMEs",
    description:
      "BI dashboards, data collection templates, and analytics playbook for businesses with no data team.",
    longDescription:
      "You don't need a data science team to make data-driven decisions. This starter kit gives business owners and ops managers everything they need to build a basic data infrastructure, create actionable dashboards, and start making decisions backed by evidence rather than instinct.",
    includes: [
      "Data collection framework and templates",
      "10 pre-built Excel BI dashboards",
      "KPI selection guide by business function",
      "Google Data Studio setup guide",
      "Data governance basics checklist",
      "Analytics skill-building reading list",
    ],
    format: "Excel + PDF",
    price: 1799,
    rating: 4.3,
    reviews: 34,
    sectors: ["All Sectors"],
    bestseller: false,
    lastUpdated: "Nov 2025",
    previewItems: [
      "Section 1: What data to collect and how",
      "Section 2: Building your first dashboard",
      "Section 3: Sales & revenue analytics",
      "Section 4: Operations metrics",
      "Section 5: Marketing analytics",
    ],
  },
  {
    id: "10",
    slug: "pricing-strategy-workshop-kit",
    category: "Strategy",
    categoryColor: "bg-eccellere-gold/20 text-eccellere-gold",
    title: "Pricing Strategy Workshop Kit",
    description:
      "Value-based pricing models, competitor benchmarking, and margin optimisation frameworks.",
    longDescription:
      "Most Indian MSMEs are underpricing — and leaving significant margin on the table. This workshop kit helps founders and commercial leads run a structured pricing review: from understanding customer willingness-to-pay to redesigning your pricing architecture for maximum profitability.",
    includes: [
      "Pricing strategy canvas",
      "Value-based pricing model (Excel)",
      "Competitor price benchmarking template",
      "Margin waterfall analysis",
      "Price increase communication guide",
      "Workshop facilitation deck (PowerPoint)",
    ],
    format: "Playbook",
    price: 2499,
    rating: 4.7,
    reviews: 62,
    sectors: ["Retail", "Consumer Products"],
    bestseller: false,
    lastUpdated: "Jan 2026",
    previewItems: [
      "Module 1: Understanding your pricing power",
      "Module 2: Value-based pricing methodology",
      "Module 3: Competitive benchmarking",
      "Module 4: Pricing architecture design",
      "Module 5: Implementation and change management",
    ],
  },
  {
    id: "11",
    slug: "prompt-engineering-playbook-for-business",
    category: "Agentic AI",
    categoryColor: "bg-eccellere-purple/20 text-eccellere-purple",
    title: "Prompt Engineering Playbook for Business",
    description:
      "100+ tested prompts for sales, operations, HR, and finance — tailored for Indian business context.",
    longDescription:
      "Save hours every week with 100+ business-ready prompts for ChatGPT, Claude, and Gemini. Unlike generic AI prompt guides, every prompt in this playbook is tested in real Indian business contexts — from drafting supplier contracts to creating customer win-back campaigns.",
    includes: [
      "100+ categorised business prompts (PDF)",
      "Prompt customisation guide",
      "AI tool comparison cheat sheet",
      "5 complete workflow automation examples",
      "Prompt testing and iteration checklist",
      "Monthly prompt update access (6 months)",
    ],
    format: "PDF",
    price: 799,
    rating: 4.6,
    reviews: 312,
    sectors: ["All Sectors"],
    bestseller: true,
    lastUpdated: "Mar 2026",
    previewItems: [
      "Section 1: Sales and business development prompts",
      "Section 2: Operations and SOPs",
      "Section 3: HR and recruitment prompts",
      "Section 4: Finance and reporting",
      "Section 5: Marketing and content",
    ],
  },
  {
    id: "12",
    slug: "quality-management-system-template-pack",
    category: "Process Transformation",
    categoryColor: "bg-eccellere-teal/20 text-eccellere-teal",
    title: "Quality Management System (QMS) Template Pack",
    description:
      "ISO 9001-aligned SOPs, audit checklists, and CAPA templates for manufacturing units.",
    longDescription:
      "Achieve ISO 9001 certification readiness or simply raise your quality standards with this comprehensive QMS template pack. Used by manufacturers across auto-components, food processing, and textiles, this pack includes everything needed to document, implement, and audit a quality management system.",
    includes: [
      "25 ISO 9001-aligned SOP templates",
      "Internal audit checklist (130 points)",
      "CAPA (Corrective Action/Preventive Action) template",
      "Non-conformance report templates",
      "Management review meeting agenda template",
      "Quality KPI dashboard (Excel)",
    ],
    format: "Template",
    price: 3999,
    rating: 4.8,
    reviews: 55,
    sectors: ["Manufacturing"],
    bestseller: false,
    pages: undefined,
    lastUpdated: "Feb 2026",
    previewItems: [
      "Section 1: Quality policy and objectives",
      "Section 2: Process documentation templates",
      "Section 3: Inspection and testing procedures",
      "Section 4: Non-conformance management",
      "Section 5: Audit and management review",
    ],
  },
];
