import JSZip from "jszip";
import { readFile, writeFile } from "fs/promises";
import path from "path";

/**
 * Truncate a .docx file to its first N pages and return the resulting
 * .docx as a Buffer.
 *
 * Page boundaries inside Word XML are detected via:
 *   1. `<w:lastRenderedPageBreak/>` — Word's own marker of where it last
 *      paginated the document. Present in any DOCX that has been opened
 *      in Word at least once. Most reliable signal.
 *   2. `<w:br w:type="page"/>` — explicit author-inserted page breaks.
 *
 * The function walks top-level body children (paragraphs and tables),
 * counts page boundary markers, and stops accepting children once the
 * count would exceed `maxPages`. The final `<w:sectPr>` (section
 * properties — page size, margins) is preserved so Word still opens the
 * truncated file cleanly.
 *
 * If no page boundary markers are found at all (e.g. a DOCX freshly
 * generated by a library that never opened in Word), falls back to
 * keeping the first ~40 paragraphs as a rough proxy for 5 pages.
 */
export async function truncateDocxPages(
  src: Buffer,
  maxPages = 5
): Promise<Buffer> {
  const zip = await JSZip.loadAsync(src);
  const docFile = zip.file("word/document.xml");
  if (!docFile) return src;
  const docXml = await docFile.async("string");

  const bodyOpen = docXml.indexOf("<w:body>");
  const bodyClose = docXml.lastIndexOf("</w:body>");
  if (bodyOpen < 0 || bodyClose < 0) return src;

  const bodyOpenEnd = bodyOpen + "<w:body>".length;
  const before = docXml.slice(0, bodyOpenEnd);
  const body = docXml.slice(bodyOpenEnd, bodyClose);
  const after = docXml.slice(bodyClose);

  // Capture the final document-level <w:sectPr>… </w:sectPr> if present so
  // we can re-append it after truncation.
  const sectPrRegex = /<w:sectPr\b[\s\S]*?<\/w:sectPr>\s*$/;
  const sectPrMatch = body.match(sectPrRegex);
  const finalSectPr = sectPrMatch ? sectPrMatch[0] : "";
  const bodyWithoutFinalSectPr = finalSectPr
    ? body.slice(0, body.length - finalSectPr.length)
    : body;

  // Match every top-level <w:p>…</w:p> and <w:tbl>…</w:tbl> block. This
  // is a conservative regex but works for valid OOXML.
  const blockRegex =
    /<w:p\b[^>]*\/>|<w:p\b[^>]*>[\s\S]*?<\/w:p>|<w:tbl\b[\s\S]*?<\/w:tbl>|<w:sdt\b[\s\S]*?<\/w:sdt>/g;
  const pageBoundary =
    /<w:lastRenderedPageBreak\s*\/>|<w:br[^>]*w:type\s*=\s*"page"[^>]*\/>/;

  const blocks: { text: string; pageBreaks: number }[] = [];
  let m: RegExpExecArray | null;
  while ((m = blockRegex.exec(bodyWithoutFinalSectPr)) !== null) {
    const txt = m[0];
    const breaks = (txt.match(new RegExp(pageBoundary.source, "g")) || []).length;
    blocks.push({ text: txt, pageBreaks: breaks });
  }

  if (blocks.length === 0) return src;

  // Walk blocks until the running page count exceeds maxPages. The first
  // page is always page 1; each page break marker advances to the next.
  let pageCount = 1;
  let kept: string[] = [];
  let foundAnyBreak = false;
  for (const b of blocks) {
    if (b.pageBreaks > 0) {
      foundAnyBreak = true;
      // A block might contain >1 break (rare). Apply each.
      for (let i = 0; i < b.pageBreaks; i++) {
        pageCount++;
        if (pageCount > maxPages) break;
      }
      if (pageCount > maxPages) break;
    }
    kept.push(b.text);
  }

  // Fallback: no page break markers anywhere. Take the first ~40 blocks.
  if (!foundAnyBreak) {
    kept = blocks.slice(0, Math.min(40, blocks.length)).map((b) => b.text);
  }

  if (kept.length === blocks.length && finalSectPr) {
    // Nothing to truncate — return original
    return src;
  }

  const truncatedBody = kept.join("") + finalSectPr;
  const newDocXml = before + truncatedBody + after;
  zip.file("word/document.xml", newDocXml);

  // Preserve the headers/footers/relationships as-is. They reference fonts
  // / styles / numbering used by the kept content.
  return await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });
}

/**
 * Given a `/uploads/...` style path stored in `Asset.fileUrls`, return the
 * sibling preview path. e.g. `/uploads/assets/foo.docx` → `/uploads/assets/foo.preview.docx`.
 */
export function previewPathFor(originalRelPath: string): string {
  const dir = path.posix.dirname(originalRelPath);
  const ext = path.extname(originalRelPath);
  const base = path.basename(originalRelPath, ext);
  return path.posix.join(dir, `${base}.preview${ext}`);
}

/**
 * Generate (or regenerate) the preview .docx beside the original file. Safe
 * to call repeatedly — it always overwrites. Returns the absolute path of
 * the written preview file, or null if the source was not a .docx.
 */
export async function ensurePreviewDocx(
  absoluteOriginalPath: string,
  maxPages = 5
): Promise<string | null> {
  if (path.extname(absoluteOriginalPath).toLowerCase() !== ".docx") {
    return null;
  }
  const src = await readFile(absoluteOriginalPath);
  const truncated = await truncateDocxPages(src, maxPages);
  const dir = path.dirname(absoluteOriginalPath);
  const base = path.basename(
    absoluteOriginalPath,
    path.extname(absoluteOriginalPath)
  );
  const outPath = path.join(dir, `${base}.preview.docx`);
  await writeFile(outPath, truncated);
  return outPath;
}
